import { Inter } from "next/font/google";
import "./globals.css";
import { AppProvider } from "./authContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Document Summarizer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AppProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </AppProvider>
  );
}
